import random

num = int(input('How many random numbers?: '))
fileName = "inputFileLarge" + str(num) + ".txt"
afile = open(fileName, "w" )
for i in range(960/10):
    M=str(random.randint(5,1000))
    s = str(random.randint(5,50))
    afile.write('0 ' + M + " " + s)
    afile.write("\n")
    M=str(random.randint(5,1000))
    N = str(random.randint(5,1000))
    afile.write('1 ' + M + " " + N)
    afile.write("\n")
    M=str(random.randint(5,1000))
    afile.write('2 ' + M + " " + M)
    afile.write("\n")
    M=str(random.randint(5,1000))
    afile.write('3 ' + M + " " + M)
    afile.write("\n")
    N = str(random.randint(5,1000))
    afile.write('4 ' + N + " " + N + "\n")
    l = str(random.randint(5,1000))
    s = str(random.randint(5,1000))
    afile.write('5 ' + N + " " + N + "\n")
    l = str(random.randint(5,1000))
    s = str(random.randint(5,1000))
    afile.write("6 " + M + " " + N)
    afile.write("\n")
    n = str(random.randint(5,1000))
    afile.write("7 " + n + " " + n + "\n")
    maxgrid = str(random.randint(2,13))
    niter = str(random.randint(5,1000))
    length = str(random.randint(5,1000))
    afile.write("8 " + maxgrid + " " + length + " " + niter)
    afile.write("\n")
    M=str(random.randint(5,1000))
    N = str(random.randint(5,1000))
    afile.write("9 " + M + " " + N)
    afile.write("\n")
for i in range(32):
    M=str(random.randint(5,1000))
    s = str(random.randint(5,50))
    afile.write('0 ' + M + " " + s)
    afile.write("\n")
    M=str(random.randint(5,1000))
    N = str(random.randint(5,1000))
    afile.write('1 ' + M + " " + N)
    afile.write("\n")
afile.close()
